def releaseSigning = [
        storeFile    : providers.environmentVariable('RELEASE_STORE_FILE').orNull,
        storePassword: providers.environmentVariable('RELEASE_STORE_PASSWORD').orNull,
        keyAlias     : providers.environmentVariable('RELEASE_KEY_ALIAS').orNull,
        keyPassword  : providers.environmentVariable('RELEASE_KEY_PASSWORD').orNull,
]

android.signingConfigs.sign {
    storeFile = releaseSigning.storeFile ? file(releaseSigning.storeFile) : null
    storePassword = releaseSigning.storePassword
    keyAlias = releaseSigning.keyAlias
    keyPassword = releaseSigning.keyPassword
}

android.buildTypes.debug.signingConfig = android.signingConfigs.debug

afterEvaluate {
    tasks.named('preReleaseBuild') {
        doFirst {
            if (releaseSigning.values().any { !it }) {
                throw new GradleException('Missing release signing environment')
            }
        }
    }
}
